onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /cpu_ptb2/DUT/rst_n
add wave -noupdate /cpu_ptb2/DUT/clk
add wave -noupdate /cpu_ptb2/DUT/mem_to_cache
add wave -noupdate /cpu_ptb2/DUT/mem_data_val
add wave -noupdate /cpu_ptb2/DUT/mem_addr
add wave -noupdate /cpu_ptb2/DUT/data_valid
add wave -noupdate /cpu_ptb2/DUT/instr_cache/clk
add wave -noupdate /cpu_ptb2/DUT/pc
add wave -noupdate /cpu_ptb2/DUT/if_instr
add wave -noupdate /cpu_ptb2/DUT/instr_cache_to_mem_address
add wave -noupdate /cpu_ptb2/DUT/instr_fsm_busy
add wave -noupdate /cpu_ptb2/DUT/instr_mem_request
add wave -noupdate /cpu_ptb2/DUT/mem_to_cache
add wave -noupdate /cpu_ptb2/DUT/data_valid
add wave -noupdate /cpu_ptb2/DUT/instr_cache/address_in
add wave -noupdate /cpu_ptb2/DUT/instr_cache/block_enable
add wave -noupdate /cpu_ptb2/DUT/instr_cache/block_offset
add wave -noupdate /cpu_ptb2/DUT/instr_cache/clk
add wave -noupdate /cpu_ptb2/DUT/instr_cache/count_out
add wave -noupdate /cpu_ptb2/DUT/instr_cache/count_plus_one
add wave -noupdate /cpu_ptb2/DUT/instr_cache/counter_in
add wave -noupdate /cpu_ptb2/DUT/instr_cache/curr_state
add wave -noupdate /cpu_ptb2/DUT/instr_cache/data_array_data_in
add wave -noupdate /cpu_ptb2/DUT/instr_cache/data_out
add wave -noupdate /cpu_ptb2/DUT/instr_cache/enable
add wave -noupdate /cpu_ptb2/DUT/instr_cache/fsm_busy
add wave -noupdate /cpu_ptb2/DUT/instr_cache/fsm_busy_sel
add wave -noupdate /cpu_ptb2/DUT/instr_cache/idle_to_wait
add wave -noupdate /cpu_ptb2/DUT/instr_cache/memory_address
add wave -noupdate /cpu_ptb2/DUT/instr_cache/memory_data
add wave -noupdate /cpu_ptb2/DUT/instr_cache/memory_data_valid
add wave -noupdate /cpu_ptb2/DUT/instr_cache/memory_request
add wave -noupdate /cpu_ptb2/DUT/instr_cache/metadata_block_enable1
add wave -noupdate /cpu_ptb2/DUT/instr_cache/metadata_block_enable2
add wave -noupdate /cpu_ptb2/DUT/instr_cache/metadata_in1
add wave -noupdate /cpu_ptb2/DUT/instr_cache/metadata_in2
add wave -noupdate /cpu_ptb2/DUT/instr_cache/metadata_out1
add wave -noupdate /cpu_ptb2/DUT/instr_cache/metadata_out2
add wave -noupdate /cpu_ptb2/DUT/instr_cache/miss_detected
add wave -noupdate /cpu_ptb2/DUT/instr_cache/nxt_state
add wave -noupdate /cpu_ptb2/DUT/instr_cache/overflow_out
add wave -noupdate /cpu_ptb2/DUT/instr_cache/rst_n
add wave -noupdate /cpu_ptb2/DUT/instr_cache/set_index
add wave -noupdate /cpu_ptb2/DUT/instr_cache/tag
add wave -noupdate /cpu_ptb2/DUT/instr_cache/w_en
add wave -noupdate /cpu_ptb2/DUT/instr_cache/wait_to_idle
add wave -noupdate /cpu_ptb2/DUT/instr_cache/wait_to_wait
add wave -noupdate /cpu_ptb2/DUT/instr_cache/word_addr_hit
add wave -noupdate /cpu_ptb2/DUT/instr_cache/word_addr_miss
add wave -noupdate /cpu_ptb2/DUT/instr_cache/word_sel
add wave -noupdate /cpu_ptb2/DUT/instr_cache/wr_data_in
add wave -noupdate /cpu_ptb2/DUT/instr_cache/write_data_array
add wave -noupdate /cpu_ptb2/DUT/instr_cache/write_tag_array1
add wave -noupdate /cpu_ptb2/DUT/instr_cache/write_tag_array2
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {165 ns} 0}
quietly wave cursor active 1
configure wave -namecolwidth 224
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 2
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ns
update
WaveRestoreZoom {0 ns} {934 ns}
